const TEAMS_DATA = {
// ==================== GRUPO A ====================
'México': {
  fifaRanking: 14, group: 'A',
  coach: { name: 'Javier Aguirre', nationality: 'Mexicana', style: 'Pragmático y defensivo', formation: '4-3-3' },
  stats: { goalsFor: 1.5, goalsAgainst: 0.9, possession: 52, corners: 5.2, fouls: 13, yellowCards: 2.1, redCards: 0.1, shots: 12.5, shotsOnTarget: 4.8, passAccuracy: 84, cleanSheets: 4, tackles: 18, interceptions: 11, saves: 3.2 },
  recentMatches: [
    { date: '2026-06-01', opponent: 'Guatemala', result: 'W', gf: 3, ga: 0, possession: 62 },
    { date: '2026-05-28', opponent: 'Perú', result: 'D', gf: 1, ga: 1, possession: 48 },
    { date: '2026-03-26', opponent: 'Honduras', result: 'W', gf: 2, ga: 0, possession: 58 },
    { date: '2026-03-22', opponent: 'Costa Rica', result: 'W', gf: 1, ga: 0, possession: 55 },
    { date: '2025-11-18', opponent: 'Canadá', result: 'D', gf: 1, ga: 1, possession: 47 },
    { date: '2025-11-14', opponent: 'Panamá', result: 'W', gf: 2, ga: 1, possession: 53 },
    { date: '2025-10-14', opponent: 'Estados Unidos', result: 'L', gf: 0, ga: 2, possession: 44 },
    { date: '2025-10-10', opponent: 'Jamaica', result: 'W', gf: 3, ga: 1, possession: 56 },
    { date: '2025-09-09', opponent: 'El Salvador', result: 'W', gf: 2, ga: 0, possession: 60 },
    { date: '2025-09-05', opponent: 'Colombia', result: 'L', gf: 1, ga: 2, possession: 45 }
  ],
  players: [
    { name: 'Guillermo Ochoa', pos: 'POR', club: 'Salernitana', age: 40 },
    { name: 'Luis Malagón', pos: 'POR', club: 'América', age: 27 },
    { name: 'Carlos Acevedo', pos: 'POR', club: 'Santos Laguna', age: 28 },
    { name: 'Jorge Sánchez', pos: 'DEF', club: 'Cruz Azul', age: 28 },
    { name: 'César Montes', pos: 'DEF', club: 'Almería', age: 29 },
    { name: 'Johan Vásquez', pos: 'DEF', club: 'Genoa', age: 27 },
    { name: 'Jesús Gallardo', pos: 'DEF', club: 'Monterrey', age: 31 },
    { name: 'Gerardo Arteaga', pos: 'DEF', club: 'Genk', age: 28 },
    { name: 'Kevin Álvarez', pos: 'DEF', club: 'Pachuca', age: 27 },
    { name: 'Jesús Angulo', pos: 'DEF', club: 'Tigres', age: 28 },
    { name: 'Israel Reyes', pos: 'DEF', club: 'América', age: 24 },
    { name: 'Edson Álvarez', pos: 'MED', club: 'West Ham', age: 28 },
    { name: 'Luis Romo', pos: 'MED', club: 'Monterrey', age: 30 },
    { name: 'Orbelín Pineda', pos: 'MED', club: 'AEK Atenas', age: 30 },
    { name: 'Carlos Rodríguez', pos: 'MED', club: 'Cruz Azul', age: 28 },
    { name: 'Érick Sánchez', pos: 'MED', club: 'PSV', age: 25 },
    { name: 'Marcel Ruiz', pos: 'MED', club: 'Sporting Gijón', age: 24 },
    { name: 'Diego Lainez', pos: 'MED', club: 'Tigres', age: 26 },
    { name: 'Roberto Alvarado', pos: 'MED', club: 'Guadalajara', age: 28 },
    { name: 'Alexis Vega', pos: 'DEL', club: 'Toluca', age: 28 },
    { name: 'Hirving Lozano', pos: 'DEL', club: 'San Diego FC', age: 30 },
    { name: 'Santiago Giménez', pos: 'DEL', club: 'Feyenoord', age: 25 },
    { name: 'Julián Quiñones', pos: 'DEL', club: 'América', age: 29 },
    { name: 'Henry Martín', pos: 'DEL', club: 'América', age: 33 },
    { name: 'César Huerta', pos: 'DEL', club: 'Pumas', age: 23 },
    { name: 'Guillermo Martínez', pos: 'DEL', club: 'Pumas', age: 29 }
  ],
  strengths: 'Solidez defensiva y experiencia mundialista; afición local como factor determinante.',
  weaknesses: 'Falta de gol en partidos de alta exigencia y transiciones lentas.',
  playStyle: 'Equipo pragmático que prioriza la solidez defensiva y busca transiciones rápidas con extremos veloces.'
},
'Sudáfrica': {
  fifaRanking: 60, group: 'A',
  coach: { name: 'Hugo Broos', nationality: 'Belga', style: 'Disciplinado y táctico', formation: '4-3-3' },
  stats: { goalsFor: 1.2, goalsAgainst: 1.0, possession: 48, corners: 4.1, fouls: 14, yellowCards: 2.3, redCards: 0.1, shots: 10.2, shotsOnTarget: 3.5, passAccuracy: 78, cleanSheets: 3, tackles: 20, interceptions: 12, saves: 4.0 },
  recentMatches: [
    { date: '2026-06-02', opponent: 'Zambia', result: 'W', gf: 2, ga: 0, possession: 52 },
    { date: '2026-05-28', opponent: 'Angola', result: 'D', gf: 1, ga: 1, possession: 46 },
    { date: '2026-03-25', opponent: 'Nigeria', result: 'L', gf: 0, ga: 1, possession: 42 },
    { date: '2026-03-21', opponent: 'Zimbabue', result: 'W', gf: 3, ga: 1, possession: 55 },
    { date: '2025-11-18', opponent: 'Benín', result: 'W', gf: 2, ga: 0, possession: 53 },
    { date: '2025-11-14', opponent: 'Ruanda', result: 'W', gf: 1, ga: 0, possession: 50 },
    { date: '2025-10-13', opponent: 'Nigeria', result: 'D', gf: 1, ga: 1, possession: 44 },
    { date: '2025-10-09', opponent: 'Zimbabue', result: 'W', gf: 2, ga: 0, possession: 54 },
    { date: '2025-09-09', opponent: 'Benín', result: 'D', gf: 0, ga: 0, possession: 47 },
    { date: '2025-09-05', opponent: 'Ruanda', result: 'W', gf: 1, ga: 0, possession: 51 }
  ],
  players: [
    { name: 'Ronwen Williams', pos: 'POR', club: 'Mamelodi Sundowns', age: 32 },
    { name: 'Veli Mothwa', pos: 'POR', club: 'AmaZulu', age: 33 },
    { name: 'Bruce Bvuma', pos: 'POR', club: 'Kaizer Chiefs', age: 29 },
    { name: 'Mothobi Mvala', pos: 'DEF', club: 'Mamelodi Sundowns', age: 30 },
    { name: 'Grant Kekana', pos: 'DEF', club: 'Mamelodi Sundowns', age: 31 },
    { name: 'Siyanda Xulu', pos: 'DEF', club: 'Sekhukhune United', age: 33 },
    { name: 'Aubrey Modiba', pos: 'DEF', club: 'Mamelodi Sundowns', age: 30 },
    { name: 'Khuliso Mudau', pos: 'DEF', club: 'Mamelodi Sundowns', age: 28 },
    { name: 'Terrence Mashego', pos: 'DEF', club: 'Cape Town City', age: 25 },
    { name: 'Nkosinathi Sibisi', pos: 'DEF', club: 'Orlando Pirates', age: 27 },
    { name: 'Rushwin Dortley', pos: 'DEF', club: 'Kaizer Chiefs', age: 22 },
    { name: 'Teboho Mokoena', pos: 'MED', club: 'Mamelodi Sundowns', age: 27 },
    { name: 'Themba Zwane', pos: 'MED', club: 'Mamelodi Sundowns', age: 36 },
    { name: 'Luke Le Roux', pos: 'MED', club: 'Orlando Pirates', age: 25 },
    { name: 'Bathusi Aubaas', pos: 'MED', club: 'Stellenbosch', age: 23 },
    { name: 'Sipho Mbule', pos: 'MED', club: 'Kaizer Chiefs', age: 27 },
    { name: 'Patrick Maswanganyi', pos: 'MED', club: 'Orlando Pirates', age: 26 },
    { name: 'Monnapule Saleng', pos: 'MED', club: 'Orlando Pirates', age: 27 },
    { name: 'Elias Mokwana', pos: 'DEL', club: 'Esperance', age: 25 },
    { name: 'Iqraam Rayners', pos: 'DEL', club: 'Mamelodi Sundowns', age: 28 },
    { name: 'Percy Tau', pos: 'DEL', club: 'Al Ahly', age: 32 },
    { name: 'Lyle Foster', pos: 'DEL', club: 'Burnley', age: 26 },
    { name: 'Thembinkosi Lorch', pos: 'DEL', club: 'Orlando Pirates', age: 31 },
    { name: 'Evidence Makgopa', pos: 'DEL', club: 'Orlando Pirates', age: 25 },
    { name: 'Oswin Appollis', pos: 'DEL', club: 'Polokwane City', age: 23 },
    { name: 'Relebohile Mofokeng', pos: 'DEL', club: 'Orlando Pirates', age: 20 }
  ],
  strengths: 'Portero de clase mundial en Ronwen Williams; gran espíritu colectivo.',
  weaknesses: 'Nivel de liga local limita la competitividad internacional; poca profundidad de banquillo.',
  playStyle: 'Equipo compacto y organizado que depende del contraataque y la solidez defensiva.'
},
'Corea del Sur': {
  fifaRanking: 25, group: 'A',
  coach: { name: 'Hong Myung-bo', nationality: 'Surcoreana', style: 'Ofensivo y técnico', formation: '4-2-3-1' },
  stats: { goalsFor: 1.6, goalsAgainst: 0.8, possession: 55, corners: 5.5, fouls: 12, yellowCards: 1.8, redCards: 0.05, shots: 13.8, shotsOnTarget: 5.1, passAccuracy: 86, cleanSheets: 5, tackles: 17, interceptions: 10, saves: 3.0 },
  recentMatches: [
    { date: '2026-06-03', opponent: 'China', result: 'W', gf: 3, ga: 0, possession: 62 },
    { date: '2026-05-28', opponent: 'Japón', result: 'D', gf: 1, ga: 1, possession: 48 },
    { date: '2026-03-26', opponent: 'Jordania', result: 'W', gf: 2, ga: 0, possession: 58 },
    { date: '2026-03-22', opponent: 'Irak', result: 'W', gf: 1, ga: 0, possession: 54 },
    { date: '2025-11-19', opponent: 'Irán', result: 'D', gf: 0, ga: 0, possession: 51 },
    { date: '2025-11-14', opponent: 'Palestina', result: 'W', gf: 4, ga: 0, possession: 65 },
    { date: '2025-10-14', opponent: 'Omán', result: 'W', gf: 2, ga: 0, possession: 60 },
    { date: '2025-10-09', opponent: 'Jordania', result: 'W', gf: 1, ga: 0, possession: 56 },
    { date: '2025-09-09', opponent: 'Australia', result: 'L', gf: 1, ga: 2, possession: 52 },
    { date: '2025-09-04', opponent: 'Irak', result: 'W', gf: 3, ga: 1, possession: 57 }
  ],
  players: [
    { name: 'Kim Seung-gyu', pos: 'POR', club: 'Al Shabab', age: 36 },
    { name: 'Jo Hyeon-woo', pos: 'POR', club: 'Ulsan HD', age: 34 },
    { name: 'Song Bum-keun', pos: 'POR', club: 'Nottingham Forest', age: 26 },
    { name: 'Kim Min-jae', pos: 'DEF', club: 'Bayern Múnich', age: 29 },
    { name: 'Kim Young-gwon', pos: 'DEF', club: 'Ulsan HD', age: 36 },
    { name: 'Cho Yu-min', pos: 'DEF', club: 'VfB Stuttgart', age: 25 },
    { name: 'Kim Jin-su', pos: 'DEF', club: 'Jeonbuk', age: 33 },
    { name: 'Kim Tae-hwan', pos: 'DEF', club: 'Ulsan HD', age: 32 },
    { name: 'Park Seung-wook', pos: 'DEF', club: 'Verona', age: 25 },
    { name: 'Hong Hyun-seok', pos: 'DEF', club: 'Genk', age: 25 },
    { name: 'Seol Young-woo', pos: 'DEF', club: 'Ulsan HD', age: 27 },
    { name: 'Lee Kang-in', pos: 'MED', club: 'PSG', age: 25 },
    { name: 'Hwang In-beom', pos: 'MED', club: 'Feyenoord', age: 29 },
    { name: 'Paik Seung-ho', pos: 'MED', club: 'Jeonbuk', age: 29 },
    { name: 'Lee Jae-sung', pos: 'MED', club: 'Mainz', age: 33 },
    { name: 'Kwon Chang-hoon', pos: 'MED', club: 'Gimcheon Sangmu', age: 31 },
    { name: 'Jung Woo-young', pos: 'MED', club: 'Al Sadd', age: 36 },
    { name: 'Yang Hyun-jun', pos: 'MED', club: 'Celtic', age: 23 },
    { name: 'Son Heung-min', pos: 'DEL', club: 'Tottenham', age: 33 },
    { name: 'Hwang Hee-chan', pos: 'DEL', club: 'Wolverhampton', age: 30 },
    { name: 'Cho Gue-sung', pos: 'DEL', club: 'Midtjylland', age: 28 },
    { name: 'Oh Hyeon-gyu', pos: 'DEL', club: 'Celtic', age: 24 },
    { name: 'Joo Min-kyu', pos: 'DEL', club: 'Jeonbuk', age: 29 },
    { name: 'Lee Seung-woo', pos: 'DEL', club: 'Suwon', age: 28 },
    { name: 'Na Sang-ho', pos: 'DEL', club: 'FC Seoul', age: 30 },
    { name: 'Eom Ji-sung', pos: 'MED', club: 'Rennes', age: 23 }
  ],
  strengths: 'Son Heung-min como referente; velocidad en transiciones y disciplina táctica.',
  weaknesses: 'Dependencia excesiva de Son; defensa vulnerable ante equipos físicos.',
  playStyle: 'Fútbol dinámico y rápido con presión alta y transiciones verticales por las bandas.'
},
'Chequia': {
  fifaRanking: 40, group: 'A',
  coach: { name: 'Miroslav Koubek', nationality: 'Checa', style: 'Compacto y organizado', formation: '3-4-3' },
  stats: { goalsFor: 1.3, goalsAgainst: 1.0, possession: 49, corners: 4.8, fouls: 13.5, yellowCards: 2.0, redCards: 0.1, shots: 11.5, shotsOnTarget: 4.2, passAccuracy: 82, cleanSheets: 3, tackles: 19, interceptions: 12, saves: 3.5 },
  recentMatches: [
    { date: '2026-05-31', opponent: 'Austria', result: 'D', gf: 1, ga: 1, possession: 47 },
    { date: '2026-05-27', opponent: 'Hungría', result: 'W', gf: 2, ga: 1, possession: 48 },
    { date: '2026-03-31', opponent: 'Irlanda', result: 'W', gf: 1, ga: 0, possession: 44 },
    { date: '2026-03-27', opponent: 'Dinamarca', result: 'W', gf: 2, ga: 1, possession: 43 },
    { date: '2025-11-18', opponent: 'Georgia', result: 'W', gf: 3, ga: 1, possession: 50 },
    { date: '2025-11-14', opponent: 'Ucrania', result: 'L', gf: 1, ga: 2, possession: 45 },
    { date: '2025-10-14', opponent: 'Albania', result: 'D', gf: 0, ga: 0, possession: 46 },
    { date: '2025-10-10', opponent: 'Georgia', result: 'W', gf: 2, ga: 0, possession: 52 },
    { date: '2025-09-09', opponent: 'Montenegro', result: 'W', gf: 1, ga: 0, possession: 49 },
    { date: '2025-09-05', opponent: 'Ucrania', result: 'D', gf: 2, ga: 2, possession: 44 }
  ],
  players: [
    { name: 'Jindřich Staněk', pos: 'POR', club: 'Slavia Praga', age: 30 },
    { name: 'Vitík Jaroš', pos: 'POR', club: 'Sturm Graz', age: 23 },
    { name: 'Matěj Kovář', pos: 'POR', club: 'Bayer Leverkusen', age: 24 },
    { name: 'Robin Hranáč', pos: 'DEF', club: 'Hoffenheim', age: 25 },
    { name: 'Ladislav Krejčí', pos: 'DEF', club: 'Girona', age: 25 },
    { name: 'Tomáš Holeš', pos: 'DEF', club: 'Slavia Praga', age: 33 },
    { name: 'David Zima', pos: 'DEF', club: 'Slavia Praga', age: 26 },
    { name: 'Vladimír Coufal', pos: 'DEF', club: 'West Ham', age: 33 },
    { name: 'Martin Vitík', pos: 'DEF', club: 'Sparta Praga', age: 22 },
    { name: 'Matěj Ryneš', pos: 'DEF', club: 'Slavia Praga', age: 24 },
    { name: 'Tomáš Vlček', pos: 'DEF', club: 'Sparta Praga', age: 22 },
    { name: 'Tomáš Souček', pos: 'MED', club: 'West Ham', age: 31 },
    { name: 'Lukáš Provod', pos: 'MED', club: 'Slavia Praga', age: 29 },
    { name: 'Alex Král', pos: 'MED', club: 'Espanyol', age: 28 },
    { name: 'Michal Sadílek', pos: 'MED', club: 'Twente', age: 27 },
    { name: 'Pavel Šulc', pos: 'MED', club: 'Viktoria Plzeň', age: 25 },
    { name: 'Ondřej Lingr', pos: 'MED', club: 'Feyenoord', age: 28 },
    { name: 'Antonín Barák', pos: 'MED', club: 'Fiorentina', age: 31 },
    { name: 'Adam Hložek', pos: 'DEL', club: 'Hoffenheim', age: 24 },
    { name: 'Patrik Schick', pos: 'DEL', club: 'Bayer Leverkusen', age: 30 },
    { name: 'Mojmír Chytil', pos: 'DEL', club: 'Slavia Praga', age: 25 },
    { name: 'Jan Kuchta', pos: 'DEL', club: 'Midtjylland', age: 29 },
    { name: 'Václav Černý', pos: 'DEL', club: 'Wolfsburgo', age: 28 },
    { name: 'Matěj Jurásek', pos: 'DEL', club: 'Slavia Praga', age: 22 },
    { name: 'Tomáš Čvančara', pos: 'DEL', club: 'Borussia M.', age: 25 },
    { name: 'David Douděra', pos: 'MED', club: 'Slavia Praga', age: 27 }
  ],
  strengths: 'Gran solidez defensiva con sistema de 3 centrales; garra y compromiso colectivo.',
  weaknesses: 'Falta de creatividad en ataque y poca posesión contra rivales superiores.',
  playStyle: 'Bloque bajo compacto con salida rápida en contraataque y juego directo a los delanteros.'
},
// ==================== GRUPO B ====================
'Inglaterra': {
  fifaRanking: 4, group: 'B',
  coach: { name: 'Gareth Southgate', nationality: 'Inglesa', style: 'Equilibrado y táctico', formation: '4-2-3-1' },
  stats: { goalsFor: 2.1, goalsAgainst: 0.6, possession: 58, corners: 6.2, fouls: 9.5, yellowCards: 1.2, redCards: 0.0, shots: 14.5, shotsOnTarget: 6.1, passAccuracy: 88, cleanSheets: 6, tackles: 15, interceptions: 9, saves: 2.1 },
  recentMatches: [
    { date: '2026-06-05', opponent: 'Italia', result: 'D', gf: 1, ga: 1, possession: 52 },
    { date: '2026-05-30', opponent: 'Bélgica', result: 'W', gf: 2, ga: 0, possession: 55 },
    { date: '2026-03-26', opponent: 'Brasil', result: 'D', gf: 0, ga: 0, possession: 49 },
    { date: '2026-03-22', opponent: 'Suiza', result: 'W', gf: 3, ga: 1, possession: 60 }
  ],
  players: [
    { name: 'Jordan Pickford', pos: 'POR', club: 'Everton', age: 32 },
    { name: 'John Stones', pos: 'DEF', club: 'Man City', age: 32 },
    { name: 'Harry Maguire', pos: 'DEF', club: 'Man United', age: 33 },
    { name: 'Declan Rice', pos: 'MED', club: 'Arsenal', age: 27 },
    { name: 'Jude Bellingham', pos: 'MED', club: 'Real Madrid', age: 22 },
    { name: 'Phil Foden', pos: 'MED', club: 'Man City', age: 26 },
    { name: 'Harry Kane', pos: 'DEL', club: 'Bayern Múnich', age: 32 },
    { name: 'Bukayo Saka', pos: 'DEL', club: 'Arsenal', age: 24 }
  ],
  strengths: 'Profundidad de plantilla élite, control del mediocampo y poder ofensivo.',
  weaknesses: 'Falta de creatividad contra bloques muy cerrados; presión mediática.',
  playStyle: 'Juego de posesión paciente buscando huecos para extremos y llegadas de segunda línea.'
},
'Estados Unidos': {
  fifaRanking: 11, group: 'B',
  coach: { name: 'Gregg Berhalter', nationality: 'Estadounidense', style: 'Ofensivo y dinámico', formation: '4-3-3' },
  stats: { goalsFor: 1.8, goalsAgainst: 1.0, possession: 54, corners: 5.8, fouls: 11, yellowCards: 1.5, redCards: 0.1, shots: 13.0, shotsOnTarget: 5.5, passAccuracy: 84, cleanSheets: 4, tackles: 16, interceptions: 11, saves: 3.5 },
  recentMatches: [
    { date: '2026-06-04', opponent: 'Uruguay', result: 'D', gf: 1, ga: 1, possession: 50 },
    { date: '2026-05-29', opponent: 'Ecuador', result: 'W', gf: 2, ga: 0, possession: 53 },
    { date: '2026-03-24', opponent: 'Alemania', result: 'L', gf: 1, ga: 3, possession: 45 },
    { date: '2026-03-20', opponent: 'Jamaica', result: 'W', gf: 3, ga: 1, possession: 60 }
  ],
  players: [
    { name: 'Matt Turner', pos: 'POR', club: 'Nott Forest', age: 31 },
    { name: 'Sergiño Dest', pos: 'DEF', club: 'PSV', age: 25 },
    { name: 'Chris Richards', pos: 'DEF', club: 'Crystal Palace', age: 26 },
    { name: 'Weston McKennie', pos: 'MED', club: 'Juventus', age: 27 },
    { name: 'Tyler Adams', pos: 'MED', club: 'Bournemouth', age: 27 },
    { name: 'Giovanni Reyna', pos: 'MED', club: 'Dortmund', age: 23 },
    { name: 'Christian Pulisic', pos: 'DEL', club: 'AC Milan', age: 27 },
    { name: 'Folarin Balogun', pos: 'DEL', club: 'Mónaco', age: 24 }
  ],
  strengths: 'Gran despliegue físico, transiciones rápidas y juventud con experiencia europea.',
  weaknesses: 'Errores defensivos puntuales y falta de consistencia ante rivales top.',
  playStyle: 'Presión alta y verticalidad utilizando la velocidad de sus extremos.'
},
'Senegal': {
  fifaRanking: 18, group: 'B',
  coach: { name: 'Aliou Cissé', nationality: 'Senegalesa', style: 'Físico y directo', formation: '4-3-3' },
  stats: { goalsFor: 1.5, goalsAgainst: 0.7, possession: 48, corners: 4.5, fouls: 14, yellowCards: 2.1, redCards: 0.05, shots: 11.2, shotsOnTarget: 4.0, passAccuracy: 80, cleanSheets: 5, tackles: 21, interceptions: 14, saves: 3.2 },
  recentMatches: [
    { date: '2026-06-02', opponent: 'Argelia', result: 'D', gf: 0, ga: 0, possession: 45 },
    { date: '2026-05-28', opponent: 'Marruecos', result: 'W', gf: 1, ga: 0, possession: 42 },
    { date: '2026-03-25', opponent: 'Camerún', result: 'W', gf: 2, ga: 1, possession: 49 },
    { date: '2026-03-21', opponent: 'Egipto', result: 'D', gf: 1, ga: 1, possession: 51 }
  ],
  players: [
    { name: 'Édouard Mendy', pos: 'POR', club: 'Al-Ahli', age: 34 },
    { name: 'Kalidou Koulibaly', pos: 'DEF', club: 'Al-Hilal', age: 34 },
    { name: 'Moussa Niakhaté', pos: 'DEF', club: 'Nott Forest', age: 30 },
    { name: 'Idrissa Gueye', pos: 'MED', club: 'Everton', age: 36 },
    { name: 'Pape Matar Sarr', pos: 'MED', club: 'Tottenham', age: 23 },
    { name: 'Sadio Mané', pos: 'DEL', club: 'Al-Nassr', age: 34 },
    { name: 'Ismaïla Sarr', pos: 'DEL', club: 'Marseille', age: 28 },
    { name: 'Nicolas Jackson', pos: 'DEL', club: 'Chelsea', age: 24 }
  ],
  strengths: 'Defensa muy sólida y presencia física imponente en mediocampo.',
  weaknesses: 'Dependencia de individualidades en ataque para desequilibrar.',
  playStyle: 'Sólido atrás, explotando contraataques y balón parado.'
},
'Japón': {
  fifaRanking: 17, group: 'B',
  coach: { name: 'Hajime Moriyasu', nationality: 'Japonesa', style: 'Intenso y técnico', formation: '4-2-3-1' },
  stats: { goalsFor: 2.2, goalsAgainst: 0.9, possession: 52, corners: 5.5, fouls: 10, yellowCards: 1.1, redCards: 0.0, shots: 13.5, shotsOnTarget: 5.8, passAccuracy: 85, cleanSheets: 4, tackles: 14, interceptions: 12, saves: 2.8 },
  recentMatches: [
    { date: '2026-06-03', opponent: 'Australia', result: 'W', gf: 2, ga: 1, possession: 55 },
    { date: '2026-05-29', opponent: 'Arabia Saudita', result: 'W', gf: 3, ga: 0, possession: 58 },
    { date: '2026-03-24', opponent: 'Alemania', result: 'D', gf: 2, ga: 2, possession: 40 },
    { date: '2026-03-20', opponent: 'Corea del Sur', result: 'W', gf: 1, ga: 0, possession: 51 }
  ],
  players: [
    { name: 'Zion Suzuki', pos: 'POR', club: 'Sint-Truiden', age: 23 },
    { name: 'Takehiro Tomiyasu', pos: 'DEF', club: 'Arsenal', age: 27 },
    { name: 'Ko Itakura', pos: 'DEF', club: 'Borussia M.', age: 29 },
    { name: 'Wataru Endo', pos: 'MED', club: 'Liverpool', age: 33 },
    { name: 'Hidemasa Morita', pos: 'MED', club: 'Sporting CP', age: 31 },
    { name: 'Kaoru Mitoma', pos: 'DEL', club: 'Brighton', age: 29 },
    { name: 'Takefusa Kubo', pos: 'MED', club: 'Real Sociedad', age: 25 },
    { name: 'Ayase Ueda', pos: 'DEL', club: 'Feyenoord', age: 27 }
  ],
  strengths: 'Juego colectivo impecable, técnica en espacios reducidos y alta intensidad.',
  weaknesses: 'Falta de biotipo físico frente a selecciones europeas o africanas.',
  playStyle: 'Juego de toque rápido, movilidad constante y presión coordinada.'
}
};
